### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by madc** [taskworld/flowcpp#11]
I'm thinking about to pack this lib into an addon for [openFrameworks](http://openframeworks.cc). Would you add a licence to this project?

Thanks.

**Comment by benwart** [comment]
I'm looking into using this project and also need to know what license it falls under before I can even hope to try it.

**Comment by jimbeveridge** [comment]
Please assign a license to this project. Without a license, it's a copyright violation for me to even clone the repo.

**Comment by kittinunf** [comment]
Sorry folks. This repo was kind of unchecked for quite some times. I have open #13 to take care of this. Hopefully it gets merged in soon.
